/**
 * ML Topics Configuration
 * Machine Learning topics - content and questions generated by Gemini API
 */

export interface Topic {
  id: string;
  name: string;
  icon: string;
  levels: number;
  color: string;
}

export const ML_TOPICS: Topic[] = [
  { id: 'linear-regression', name: 'Linear Regression', icon: '📊', levels: 3, color: '#3b82f6' },
  { id: 'logistic-regression', name: 'Logistic Regression', icon: '🔀', levels: 3, color: '#10b981' },
  { id: 'loss-functions', name: 'Loss Functions', icon: '📈', levels: 2, color: '#f59e0b' },
  { id: 'gradient-descent', name: 'Gradient Descent', icon: '⬇️', levels: 3, color: '#06b6d4' },
  { id: 'neural-networks', name: 'Neural Networks', icon: '🧠', levels: 4, color: '#8b5cf6' },
  { id: 'decision-trees', name: 'Decision Trees', icon: '🌳', levels: 2, color: '#ec4899' },
];
