/**
 * ML Topics Configuration
 * Machine Learning topics - content and questions generated by Gemini API
 */

export interface Topic {
  id: string;
  name: string;
  icon: string;
  levels: number;
  color: string;
}

export const ML_TOPICS: Topic[] = [
  { id: 'introduction-to-ml', name: 'Introduction to ML', icon: '📊', levels: 3, color: '#3b82f6' },
  { id: 'working-with-data', name: 'Working with Data', icon: '🔀', levels: 3, color: '#10b981' },
  { id: 'supervised-learning-basics', name: 'Supervised Learning Basics', icon: '📈', levels: 3, color: '#f59e0b' },
  { id: 'unsupervised-learning-basics', name: 'Unsupervised Learning Basics', icon: '⬇️', levels: 3, color: '#06b6d4' },
  { id: 'environmental-impact-of-ml', name: 'Environmental Impact of ML', icon: '🧠', levels: 2, color: '#8b5cf6' },
];
